NETOBSERV-287 Aggregate stats, fix limit reach
netobserv/network-observability-console-plugin pull request #136
Opened 2022-04-27 15:20 UTC by jotak

- Stats are now aggregated in backend (needed when multiple queries are performed)
- Add a few tests
- On the frontend, limit reached now comes as a stats provided from
  backend
- Add info tooltip on limit setting, to clarify it's the limit per loki
  query, so we may end up with more flows than this limit

2022-04-29 09:22 UTC, jpinsonneau requested changes
Can't access to topology view anymore:

```
Unable to get topology
TypeError: Cannot read properties of undefined (reading 'result')
```

It would be great to show stats as JSON in the summary panel. Feel free to create a followup task if you prefer.

2022-04-29 09:22 UTC, jpinsonneau commented on web/src/api/routes.ts
> +    };
Need to do the same logic in `getTopology`

2022-04-29 09:22 UTC, jpinsonneau commented on web/src/components/netflow-traffic.tsx
> +          })
Also update `case 'topology':` below

2022-04-29 09:23 UTC, jpinsonneau commented on web/src/api/routes.ts
> +    };
`return (r.data.data.result as TopologyMetrics[])` needs to be `return (r.data.result as TopologyMetrics[])`

2022-04-29 11:21 UTC, jotak commented
Thanks, yeah I forgot about topology on the frontend, should be fixed now.

2022-04-29 12:41 UTC, jpinsonneau approved these changes
LGTM, thanks @jotak !

2022-04-29 12:53 UTC, jotak commented
thanks Julien
holding for pending release
/hold

2022-05-04 12:22 UTC, jotak commented
/unhold
/approve

2022-05-04 12:33 UTC, merged