NETOBSERV-1200 UI: DNSTracking feedback improvments
netobserv/network-observability-console-plugin pull request #361
Opened 2023-07-25 12:05 UTC by jpinsonneau

2023-07-28 08:28 UTC, jpinsonneau commented
Setting this PR as ready for review since it's already quite big
-> max / p90 / p99  can be done in a followup PR

2023-07-31 11:23 UTC, msherif1234 reviewed
/LGTM however the logic `moreThanRegex`  looks too complex but u added UT for it so should be stable we can improve after the PR is merged

2023-07-31 11:24 UTC, msherif1234 commented
/lgtm

2023-07-31 13:19 UTC, jpinsonneau commented
> /LGTM however the logic `moreThanRegex` looks too complex but u added UT for it so should be stable we can improve after the PR is merged

Yes I agree. If you have an easier approach in mind I'm in :smile_cat: 

Else @jotak [suggested to maintain a static list of value - regex for 1 / 10 / 100 ms](https://redhat-internal.slack.com/archives/C02939DP5L5/p1690379012079529?thread_ts=1690373502.510909&cid=C02939DP5L5). The downside is that it may not apply to any number fields in future.

2023-08-01 18:10 UTC, memodi commented
/ok-to-test

2023-08-01 20:42 UTC, memodi commented on pkg/loki/filter.go
> +	sb.WriteString("^(")
I don't get correct results with `^` here , it's not the start of the line is it? I tried without carat and matches well: https://regex101.com/r/l8OWLf/1

2023-08-01 20:54 UTC, memodi requested changes
moreThan fails to match

2023-08-02 08:19 UTC, jpinsonneau commented
> moreThan fails to match

Good catch @memodi, sorry about that. I tried to manage more cases but ended breaking it :angel: 
I removed the start match as you suggested https://github.com/netobserv/network-observability-console-plugin/pull/361/commits/01c1c48256445f92d07f0b5b3ee39be30a7939d0 since it's managed by the prefix part `DnsLatencyMs\":`
Thanks !

2023-08-02 16:07 UTC, memodi commented
/label qe-approved 
thanks @jpinsonneau for incorporating feedback.

2023-08-02 16:20 UTC, msherif1234 commented
/lgtm

2023-08-03 06:40 UTC, jpinsonneau commented
/approve

2023-08-03 06:46 UTC, merged